-- init.sql
CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    email VARCHAR(255) UNIQUE,
    is_admin BOOLEAN NOT NULL,
    status VARCHAR(50),
    password VARCHAR(255) NOT NULL
);
CREATE TABLE tickets (
    id BIGINT PRIMARY KEY,             
    client_id BIGINT NOT NULL,                         
    creation_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    concert_hall VARCHAR(10) NOT NULL,                 
    event_code INT NOT NULL,                           
    is_promo BOOLEAN DEFAULT FALSE,                    
    stadium_sector VARCHAR(255),                       
    max_backpack_weight NUMERIC,                        
    price DECIMAL(10, 2) NOT NULL,                     
    CONSTRAINT fk_client FOREIGN KEY (client_id)
    REFERENCES clients(id)     
);
